### ISSUE TITLE
Site Completely broken on iPad

### ISSUE THREAD

**Issue by sherred** [whiskyweb/whiskyweb-website#38]
I have a first generation iPad and the site is completely broekn on it, the background is all white and text is all missplaced

**Comment by juokaz** [comment]
Noted, looking into it

**Comment by d0ugal** [comment]
I was looking into this - but since it's not as broken on the iPad 2 I couldn't see it failing - until I tried IE8.

http://s.do.ugal.me/1100303b1x1B3L1Q3Q1N

(I'm assuming this is exactly the same issue - the description certainly sounds the same)

**Comment by d0ugal** [comment]
Not a trivial fix really - had a quick poke around with IE8 to reproduce.

On load there is JavaScript error due to `$('navigation a')` not working and thus the links object doesn't have any values and `highlightNavAtPosition` fails.

Basically the use of HTML5 elements is breaking selectors in the JavaScript and CSS. Still don't know if its the same problem in the iPad one - but presumably it is. I done some quite search and replace changes to swap back to divs with class names and it started to look better but not sure this is the route you want to go.

**Comment by juokaz** [comment]
I fixed the navigation error, something I forgot to fix this morning. Also added modernizr, this should make selectors work now, does it>

**Comment by d0ugal** [comment]
Good call. Significantly better. http://s.do.ugal.me/1P0e3S441M0f1L0Y443x

It's now perfectly usable - there are just a few tweaks and visual touches that you can see are missing.

**Comment by juokaz** [comment]
This also appears to have somewhat fixed mobile view. It almost works on my blackberry. There are some bugs (navigation should be hidden, seems `nav` selector still doesnt work, there is some white space on a right), but now you can actually read it.
